import type { RecoveryPlan, Patient } from "@/types";
import type { RiskAssessment } from "@/types/risk-assessment";
import { assessRisk } from "./risk-assessment";

export const MOCK_PATIENT: Patient = {
  id: "patient-001",
  name: "Marcus Johnson",
  dateOfBirth: "1978-04-12",
  dischargeDate: "2026-04-17",
  condition: "Knee Replacement Surgery (Right)",
  surgeon: "Dr. Sarah Chen",
  primaryCare: "Dr. David Park",
  followUpDate: "2026-05-01",
};

export const MOCK_RECOVERY_PLAN: RecoveryPlan = {
  id: "plan-001",
  patientId: "patient-001",
  status: "on_track",
  confidenceScore: 87,
  daysSinceDischarge: 7,
  totalRecoveryDays: 84,
  lastUpdated: new Date().toISOString(),
  medications: [
    {
      id: "med-1",
      name: "Oxycodone",
      dosage: "5mg",
      frequency: "twice_daily",
      instructions: "Take with food. Do not drive.",
      purpose: "Used to manage moderate to severe pain after surgery",
      startDate: "2026-04-17",
      endDate: "2026-04-24",
      taken: true,
      nextDose: "8:00 PM",
      color: "#3B82F6",
    },
    {
      id: "med-2",
      name: "Ibuprofen",
      dosage: "600mg",
      frequency: "three_times_daily",
      instructions: "Take with food or milk.",
      purpose: "Used to reduce pain and swelling",
      startDate: "2026-04-17",
      endDate: "2026-05-17",
      taken: false,
      nextDose: "2:00 PM",
      color: "#10B981",
    },
    {
      id: "med-3",
      name: "Aspirin",
      dosage: "81mg",
      frequency: "once_daily",
      instructions: "Take in the morning to prevent blood clots.",
      purpose: "Used to prevent blood clots and reduce risk of complications",
      startDate: "2026-04-17",
      endDate: "2026-07-17",
      taken: true,
      nextDose: "Tomorrow 8:00 AM",
      color: "#8B5CF6",
    },
    {
      id: "med-4",
      name: "Pantoprazole",
      dosage: "40mg",
      frequency: "once_daily",
      instructions: "Take 30 min before breakfast.",
      purpose: "Used to protect your stomach from irritation caused by other medications",
      startDate: "2026-04-17",
      endDate: "2026-05-17",
      taken: false,
      nextDose: "8:00 AM",
      color: "#F59E0B",
    },
  ],
  tasks: [
    {
      id: "task-1",
      title: "Morning Physical Therapy Exercises",
      description: "Complete 15-minute PT routine: ankle pumps, quad sets, heel slides.",
      category: "exercise",
      dueDate: new Date().toISOString(),
      completed: true,
      priority: "high",
    },
    {
      id: "task-2",
      title: "Ice Knee (20 minutes)",
      description: "Apply ice pack to surgical site for swelling management.",
      category: "wound_care",
      dueDate: new Date().toISOString(),
      completed: true,
      priority: "medium",
    },
    {
      id: "task-3",
      title: "Evening Walk",
      description: "Short 5-10 minute walk with walker to build mobility.",
      category: "exercise",
      dueDate: new Date().toISOString(),
      completed: false,
      priority: "high",
    },
    {
      id: "task-4",
      title: "Wound Dressing Check",
      description: "Check surgical wound for redness, drainage, or unusual swelling.",
      category: "wound_care",
      dueDate: new Date().toISOString(),
      completed: false,
      priority: "high",
    },
    {
      id: "task-5",
      title: "Log Daily Symptoms",
      description: "Record pain level, mobility, and energy in the symptom tracker.",
      category: "monitoring",
      dueDate: new Date().toISOString(),
      completed: false,
      priority: "medium",
    },
  ],
  warningSigns: [
    {
      id: "warn-1",
      title: "Signs of Deep Vein Thrombosis",
      description: "Sudden calf pain, swelling, redness, or warmth in the leg.",
      severity: "critical",
      actionRequired: "Call 911 or go to ER immediately.",
    },
    {
      id: "warn-2",
      title: "Infection Signs",
      description: "Increased redness, warmth, pus, or fever above 101.5°F.",
      severity: "critical",
      actionRequired: "Call Dr. Chen's office within 1 hour.",
    },
    {
      id: "warn-3",
      title: "Unusual Swelling",
      description: "Knee swelling significantly larger than previous day.",
      severity: "warning",
      actionRequired: "Contact care team within 24 hours.",
    },
  ],
  milestones: [
    {
      id: "ms-1",
      title: "Home Safely",
      description: "Successfully discharged from hospital",
      targetDate: "2026-04-17",
      achieved: true,
      achievedDate: "2026-04-17",
      icon: "Home",
    },
    {
      id: "ms-2",
      title: "Walking with Walker",
      description: "Independent mobility with assistive device",
      targetDate: "2026-04-20",
      achieved: true,
      achievedDate: "2026-04-19",
      icon: "PersonStanding",
    },
    {
      id: "ms-3",
      title: "Stairs Independently",
      description: "Navigate stairs without assistance",
      targetDate: "2026-04-28",
      achieved: false,
      icon: "MoveUp",
    },
    {
      id: "ms-4",
      title: "Walker-Free Walking",
      description: "Walk short distances without any assistive device",
      targetDate: "2026-05-08",
      achieved: false,
      icon: "Footprints",
    },
    {
      id: "ms-5",
      title: "Full Knee Bend (90°)",
      description: "Achieve 90 degrees of knee flexion",
      targetDate: "2026-05-17",
      achieved: false,
      icon: "Activity",
    },
    {
      id: "ms-6",
      title: "Return to Daily Activities",
      description: "Drive, cook, and resume light work",
      targetDate: "2026-06-17",
      achieved: false,
      icon: "Sparkles",
    },
  ],
  symptoms: [
    { id: "s-1", name: "Knee Pain", severity: "mild", reportedAt: new Date().toISOString(), notes: "Mostly in the morning" },
    { id: "s-2", name: "Swelling", severity: "mild", reportedAt: new Date().toISOString() },
    { id: "s-3", name: "Fatigue", severity: "moderate", reportedAt: new Date().toISOString() },
  ],
  symptomHistory: [
    { date: "Apr 17", pain: 8, energy: 2, mobility: 2, sleep: 4, overall: 3 },
    { date: "Apr 18", pain: 7, energy: 3, mobility: 3, sleep: 5, overall: 4 },
    { date: "Apr 19", pain: 6, energy: 4, mobility: 4, sleep: 6, overall: 5 },
    { date: "Apr 20", pain: 5, energy: 5, mobility: 5, sleep: 7, overall: 6 },
    { date: "Apr 21", pain: 5, energy: 6, mobility: 6, sleep: 7, overall: 6 },
    { date: "Apr 22", pain: 4, energy: 6, mobility: 6, sleep: 8, overall: 7 },
    { date: "Apr 23", pain: 3, energy: 7, mobility: 7, sleep: 8, overall: 7 },
    { date: "Apr 24", pain: 3, energy: 7, mobility: 7, sleep: 8, overall: 8 },
  ],
  aiInsights: [
    "Pain levels have decreased 62% since discharge — excellent progress.",
    "Mobility scores trending above post-op average for Day 7.",
    "Medication adherence at 89% — maintain current schedule.",
    "Next follow-up with Dr. Chen recommended on April 28.",
  ],
};

// Generate mock risk assessment based on recovery plan data
export const MOCK_RISK_ASSESSMENT: RiskAssessment = assessRisk({
  patientId: MOCK_PATIENT.id,
  currentPainLevel: 3,
  recentSymptoms: ["swelling", "fatigue"],
  daysSinceDischarge: MOCK_RECOVERY_PLAN.daysSinceDischarge,
  medicationAdherence: 89,
  recentSymptomHistory: MOCK_RECOVERY_PLAN.symptomHistory.map((s) => ({
    date: s.date,
    pain: s.pain,
  })),
  condition: MOCK_PATIENT.condition,
});
